### ISSUE TITLE
Translation based on fixed reference vector

### ISSUE THREAD

**Issue by fkunzweiler** [grundy95/changepoint.geo#31]
Dear @grundy95, 

I have a question regarding your method.

According to equation 2.1 in the publication (https://doi.org/10.1007/s11222-020-09940-y),
the subtracted value is the minimum over the time series for each dimension individually.
Looking at the implementation it seems that you subtract the minimum over the dimensions for each time-step individually.

https://github.com/grundy95/changepoint.geo/blob/fa5bdf4a6997fb84dd508d55bd9f14147d460728/R/geomcp.R#L98

I think line L98 should be:
min.X <- apply(X,1,min)-ref.vec.value

**Comment by grundy95** [comment]
Hi, 
The subtracted value should be the minimum over the whole time series for each dimension individually. As the data matrix in an n x p matrix, each new row is a new time point. Hence, to get the minimum over the whole time series for each dimension, you need the minimum of each column - as such the apply function is applied for each column. This gives a vector of length p with the minimum in each dimension, which is then subtracted from each time point individually.

I hope this helps solve the issue?

**Comment by fkunzweiler** [comment]
Hi,
thank you for the fast reply.

Yes you are correct, I got confused by the R syntax being different over python.
